/*
* GNAR POWER AUDIT TESTING
* CHRIS PARK
*
*/
use GNAR_DEV;

WITH ATOLL AS(
	SELECT -- *
	A.PULLDATE,
	A.SITE_NAME,
	A.ENODEB,
	A.EUTRANCELLFDD,
	T.TX_ID,
	C.CELL_ID,
	--
	A.ENM_NOOFTX,
	T.N_TX_ANTENNAS AS TX_N_TX_ANTENNAS,
	A.ENM_NOOFRX,
	T.N_RX_ANTENNAS AS TX_N_RX_ANTENNAS,
	T.N_TX_PA AS TX_N_TX_PA, 
	A.ENM_MAXTXPWR,
	ROUND(A.ENM_REF_BRANCH_DBM,1) AS ENM_BRANCH_DBM,
	ROUND(C.MAX_POWER,1) AS CELL_MAX_POWER,
	ROUND(T.MISCDLL,2) AS MISCDLL,
	ROUND(A.ENM_CRSGAIN,2) AS ENM_CRSGAIN,
	(CASE WHEN A.ENM_CRSGAIN = 0 THEN 1
	WHEN A.ENM_CRSGAIN = 3 THEN 2
	WHEN A.ENM_CRSGAIN = 6 THEN 4 
	ELSE 0 END) AS ENM_CRSPORTS,
	C.N_CRS_PORTS,
	C.PBCH_POWER_OFFSET
--
--
FROM [GNAR_DEV].[dbo].[NETWORK_STATUS_20240130] A
JOIN [dbo].[CELLS_ATOLLv1] C ON C.CELL_ID = A.EUTRANCELLFDD
JOIN [dbo].[CELL_ID_ATOLLv1] ID ON ID.CELL_ID = C.CELL_ID
JOIN [dbo].[TX_ATOLLv2] T ON T.TX_ID = ID.TX_ID
WHERE 1=1 
-- AND A.ENODEB = 'UNL05823'
AND A.ENODEB LIKE 'UN%'
AND A.FREQBAND IN (4,66,2,17,5,29,66)
-- AND A.ENM_CRSGAIN NOT IN (3,6)
-- AND ROUND(A.ENM_REF_BRANCH_DBM,1) <> ROUND(C.MAX_POWER,1)
-- AND (ROUND(A.ENM_REF_BRANCH_DBM,1) <> ROUND(C.MAX_POWER,1) OR A.ENM_NOOFTX <> T.N_TX_ANTENNAS)
)
------------------------------------------------------------------------------------
SELECT 
(CASE WHEN (AT.ENM_BRANCH_DBM <> AT.CELL_MAX_POWER) AND (AT.N_CRS_PORTS <> AT.ENM_CRSPORTS) AND (AT.TX_N_TX_ANTENNAS <> AT.ENM_NOOFTX) THEN 'TX_BRANCH CL_PWR CL_CRSPORT'
WHEN (AT.ENM_BRANCH_DBM <> AT.CELL_MAX_POWER) AND (AT.TX_N_TX_ANTENNAS <> AT.ENM_NOOFTX) THEN 'TX_BRANCH CL_PWR'
WHEN (AT.ENM_BRANCH_DBM <> AT.CELL_MAX_POWER) AND (AT.N_CRS_PORTS <> AT.ENM_CRSPORTS) THEN 'CL_PWR CL_CRSPORT'
WHEN (AT.N_CRS_PORTS <> AT.ENM_CRSPORTS) AND (AT.TX_N_TX_ANTENNAS <> AT.ENM_NOOFTX) THEN 'TX_BRANCH CL_CRSPORT'
WHEN (AT.ENM_BRANCH_DBM <> AT.CELL_MAX_POWER) THEN 'CL_PWR'
WHEN (AT.N_CRS_PORTS <> AT.ENM_CRSPORTS) THEN 'CL_CRSPORT'
WHEN (AT.TX_N_TX_ANTENNAS <> AT.ENM_NOOFTX) THEN 'TX_BRANCH'
ELSE NULL END) AS ATOLL_FLAG,
AT.*
FROM ATOLL AT
WHERE 1=1
-- AND AT.TX_N_TX_ANTENNAS <> AT.ENM_NOOFTX
-- AND AT.N_CRS_PORTS <> AT.ENM_CRSPORTS
-- AND AT.ENM_BRANCH_DBM <> AT.CELL_MAX_POWER
AND (AT.ENM_BRANCH_DBM <> AT.CELL_MAX_POWER OR AT.N_CRS_PORTS <> AT.ENM_CRSPORTS OR AT.TX_N_TX_ANTENNAS <> AT.ENM_NOOFTX)
;